sonar.projectKey=steveenr-a_anicv1
sonar.organization=steveenr-a
sonar.host.url=https://sonarcloud.io

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=AniCS
sonar.projectVersion=0.2.4

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src,src-tauri/src
sonar.tests=src,src-tauri/tests
sonar.test.inclusions=**/__tests__/**,**/*.test.ts,**/*.test.tsx,src-tauri/tests/**
sonar.exclusions=**/__tests__/**,**/*.test.ts,**/*.test.tsx,**/node_modules/**,**/dist/**,**/target/**,**/gen/**,**/*.keystore,**/*.txt,**/public/**

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
